### ISSUE TITLE
Issue: Get error: unable to open named profile (user): using the null configuration.

### ISSUE THREAD

**Issue by cristianapas** [ubuntu/adsys#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

After installing adsys I get error **unable to open named profile (user@domain): using the null configuration** while logging. I tried to join the pc to the domain using sssd and winbind and in both cases it works the same.

### Steps to reproduce it

Using Ubuntu Desktop 24.04, and Windows Server 2012r2

### Environment
* adsys version: please run `adsysctl version`
* Distribution: (**NAME** in `/etc/os-release`)
* Distribution version: (**VERSION_ID** on `/etc/os-release`):

### Log files
Please redact/remove sensitive information:
```raw
adsys service logs can be acquired by running `adsysctl service cat -v`.
You can increase the amount of information displayed by increasing the verbosity level (-v) to -vv or -vvv.
```

### Application settings
Please redact/remove sensitive information:
```raw
Paste the contents of your adsys.yaml file here, if you created one.
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by didrocks** [comment]
Do you mind expanding a bit what is the "null configuration". Also, we would need the logs and more informations about your system as requested by the template.

Thanks!

**Comment by snussbaumermpreis** [comment]
Hello,

I have just discovered the same problem. This almost made me switch back to Windows...

The problem is the following:

With the following sssd.conf:

[sssd]
domains = domain.tld
config_file_version = 2
services = nss, pam, ifp
default_domain_suffix = domain.tld

[domain/DOMAIN.TLD]
default_shell = /bin/bash
krb5_store_password_if_offline = False
cache_credentials = True
krb5_realm = DOMAIN.TLD
realmd_tags = manages-system joined-with-adcli 
id_provider = ad
ldap_sasl_authid = HOSTNAME$
fallback_homedir = /home/%u@%d
ad_domain = domain.tld
use_fully_qualified_names = True
ldap_id_mapping = True
access_provider = ad
account_cache_expiration = 1
ad_gpo_access_control = enforcing
ad_gpo_cache_timeout = 30
ad_gpo_ignore_unreadable = True
ad_hostname = HOSTNAME.DOMAIN.TLD
ad_gpo_map_remote_interactive = +nx
auto_private_groups = true
ldap_user_ssh_public_key = altSecurityIdentities
ldap_user_extra_attrs = altSecurityIdentities


I get the following error with adsys 0.14.1~22.04 previously with Version 0.9.2~22.04.1 this worked fine. 

Jul 17 15:06:09 HOSTNAME systemd[1]: Starting ADSys daemon service...
Jul 17 15:06:09 HOSTNAME adsysd[35284]: level=error msg="couldn't create adsys service: could not initialize AD backend: can't get domain configuration from {Conf:/etc/sssd/sssd.conf CacheDir:/var/lib/sss/db}:could not find AD domain section corresponding to \"domain.tld\">
Jul 17 15:06:09 HOSTNAME systemd[1]: adsysd.service: Main process exited, code=exited, status=1/FAILURE
Jul 17 15:06:09 HOSTNAME systemd[1]: adsysd.service: Failed with result 'exit-code'.
Jul 17 15:06:09 HOSTNAME systemd[1]: Failed to start ADSys daemon service.

Because of the adsys pam module, Logins now fail!

With adsys 0.14.1~22.04 and the following sssd.conf (changed the Domainname from upper to lower case):

[sssd]
domains = domain.tld
config_file_version = 2
services = nss, pam, ifp
default_domain_suffix = domain.tld

[domain/domain.tld]
default_shell = /bin/bash
krb5_store_password_if_offline = False
cache_credentials = True
krb5_realm = DOMAIN.TLD
realmd_tags = manages-system joined-with-adcli 
id_provider = ad
ldap_sasl_authid = HOSTNAME$
fallback_homedir = /home/%u@%d
ad_domain = domain.tld
use_fully_qualified_names = True
ldap_id_mapping = True
access_provider = ad
account_cache_expiration = 1
ad_gpo_access_control = enforcing
ad_gpo_cache_timeout = 30
ad_gpo_ignore_unreadable = True
ad_hostname = HOSTNAME.DOMAIN.TLD
ad_gpo_map_remote_interactive = +nx
auto_private_groups = true
ldap_user_ssh_public_key = altSecurityIdentities
ldap_user_extra_attrs = altSecurityIdentities

Adsys starts and works fine with this, but first of all, this is now a different username because that changes to lowercase too, but more importantly, when using any domain user now I cant change any GUI settings (not even Desktop backgrounds).
This is because the user no gets an environment variable: DCONF_PROFILE=username@domain.tld and that dconf profile does not exist and ~/.config/dconf/user is not created! So the user has no deconf profile where the settings could be saved as far as I understand this, so this is where the original error message is coming from: 
unable to open named profile (user@domain): using the null configuration.

So first of all adsys should still be able to parse the domainname from sssd if it is uppercase. Second and more importantly it should not mess up the users dconf.

Steps to reproduce:

Join a machine to a AD Domain with SSSD using the uppercase Domainname, then install adsys (0.14) you will get the error on service start, then change the domainname to lowercase, you wont be able (with a AD Domain User) to change any settings related to dconf/gsettings Databases.

I hope this helps. Meanwhile I will hold on to adsys 0.9.2...

**Comment by denisonbarbosa** [comment]
Hey, @snussbaumermpreis and @cristianapas! We have some suspicions about the possible cause of the issue, but before submitting any fixes, we'd like to ask you to try something if you can:

Keeping the domain configuration as you updated (with the lowercase domain), can you try configuring at least one dconf key (on the server) for the user you're trying to authenticate with?

This issue might be happening due to the user not having any dconf setting configured (which means that the user-specific profile won't be created), thus resulting in you not being able to change any user-specific dconf value.

**Comment by snussbaumermpreis** [comment]
Hello and thank you for working on this!

I can definitly confirm that this happens even if the database is present and has entries. I have tried it with a existing database both by creating it (without adsys installed) and by moving an existing database. As I understand it, this not because it cant be created.

The file is the following: ~/.config/dconf/user

But (presumably adsys) sets "DCONF_PROFILE" with the username so: DCONF_PROFILE=user@domain.tld

I renamed the file, which did not change anything.

In my seperate issue: https://github.com/ubuntu/adsys/issues/1054 I provided some more infos about this dconf part.

My understanding of dconf is pretty minimal... So I cant tell you what exactly happens but this is definetly pretty odd...

Have you been able to recreate the issue? If not I could go through the hassle once again and try to make a foolproof step by step to recreate it. I am not to keen on that though and I hope I have reported enough infos for you to provide some sort of fix.

**Comment by denisonbarbosa** [comment]
Hey, guys! The fixed version (0.14.2) is now available at [ppa:ubuntu-enterprise-desktop/adsys](https://launchpad.net/~ubuntu-enterprise-desktop/+archive/ubuntu/adsys) if you'd like to use it while we are preparing things for releasing the fixes into the archive. Thanks again for reporting the issue and helping us make adsys better!

**Comment by sebma** [comment]
> Hey, guys! The fixed version (0.14.2) is now available at [ppa:ubuntu-enterprise-desktop/adsys](https://launchpad.net/~ubuntu-enterprise-desktop/+archive/ubuntu/adsys) if you'd like to use it while we are preparing things for releasing the fixes into the archive. Thanks again for reporting the issue and helping us make adsys better!

@denisonbarbosa Thanks a LOT !!!

Your #1070 PR solved my user profil pb.

Got bless you abundantly.

**Comment by pcesarBH** [comment]
I would like to reopen this issue. I started to use SSSD/ADSys to authenticate Ubuntu AD users in our company, replacing Centrify Express which is no longer updated. Upon login, the environment variable DCONF_PROFILE is set to the AD username. No gsettings command would work and the error message is "unable to opend named profile (username): using the null configuration". As a workaround, I created a file in /etc/profile.d/ to unset DCONF_PROFILE and the issue is gone.
As a side note, there is no problem when using KDE/Plasma. I haven't test other desktops.

**Comment by pcesarBH** [comment]
I will share some new information that I have just found.  I made these modifications to the file /etc/sssd/conf:
fallback_homedir = /home/%u
use_fully_qualified_names = False

They are needed so that the AD user won't have to type the domain name when logging in. The DCONF_PROFILE is the set to "username" without the domain name. But, the profile file created in /etc/dconf/profile is created WITH the domain name. I created a hard link to this file named only "username", logged in again and the profile was recognized.

**Comment by denisonbarbosa** [comment]
Hey, @pcesarBH! Thanks for reporting back on this. ADSys always try to set the `DCONF_PROFILE` env with the FQDN username. In order to do that, we need to know the domain the user is authenticating to.

Can you double check if your `sssd.conf` file has the `default_domain_suffix` configured? If not, you need to set it to the domain you're trying to authenticate to.

Since ADSys is not about authentication (that's up to sssd), we don't have the firepower needed to test which domain the user belongs to. Instead, we rely on the `default_domain_suffix` value in `sssd.conf` to determine which domain the user belongs to (if the username is not "FQDN'ed").
