### ISSUE TITLE
Lockdown breaks dconf

### ISSUE THREAD

**Issue by LiohMoeller** [ubuntu/adsys#337]
I have configured the picture uri to disabled on Ubuntu 22.04. Afterwards I am as expected no longer able to change the wallpaper, but I can also not set any other dconf settings anymore, like changing the keyboard layout.
After setting the GPO Option back to Not Configured I can still not set the wallpaper again or any other dconf value.
The dconf configuration directory for that user ~/.config/dconf/ does not exist, nor it's created while changing a value.
I have tried to move the computer and user out of the OUs where the Policies are active, without success. Only removing adsys completely solved the issue.

**Comment by didrocks** [comment]
Hey, thanks for your bug report and your interest in adsys.

Indeed, this is something that we discovered recently with recent changes in 22.04 (there is no .config/dconf used btw, the files used are at the system default level). [v0.8.5](https://github.com/ubuntu/adsys/releases/tag/v0.8.5) fix that particular issue. It is already available in Kinetic (which will be 22.10). There is a Stable Release Update for 22.04 which is in progress.
You can try to download the deb from Kinetic to give it a try it directly: https://launchpad.net/ubuntu/+source/adsys/0.8.5/+build/23755169. If you prefer I can provide a ppa until the fix is properly available on 22.04.

**Comment by didrocks** [comment]
Closing as the v0.8.5 is now in Jammy for a week and no feedback. Feel free to reopen if this didn’t fix it for you on a new installation. Thanks!
