### ISSUE TITLE
use set-safe-directory from github action

### ISSUE THREAD

**Issue by didrocks** [ubuntu/adsys#596]
Github checkout action has a set-safe-direction attribute, use that rather than our hack.

**Comment by denisonbarbosa** [comment]
I think we are blocked by [this issue](https://github.com/actions/runner/issues/2058), since we only had the work around on actions that run on containers. The `set-safe-directory` attribute, which is `true` by default btw, is using the value from $GITHUB_WORKSPACE rather than the container directory (and it seems to also ignore the path override, despite setting it in the action).

**Comment by jibel** [comment]
workaround in place.

**Comment by SwuduSusuwu** [comment]
> workaround in place.

Am curious as to what workaround you used
